apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-remote-10-app
  namespace: ai-rhdh
  finalizers: ["resources-finalizer.argocd.argoproj.io"]
spec:
  project: default
  source:
    path: ./components/test-remote-10/overlays/development
    repoURL: https://github.com/jdubrick-ai/test-remote-10-gitops.git
    targetRevision: main
  destination:
    server: https://api.jdubrick-mar17.devcluster.openshift.com:6443
    namespace: rhdh-app
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: ai-rhdh
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
