apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  rhtap/gitops: test-remote-10
  janus-idp.io/tekton: test-remote-10
  backstage.io/kubernetes-id: test-remote-10
  backstage.io/kubernetes-namespace: rhdh-app
  app.kubernetes.io/part-of: test-remote-10
resources:
  - application-dev.yaml
  - application-tekton.yaml