apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: test-remote-10
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-remote-10
  name: test-remote-10
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
