apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: test-remote-10
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-remote-10
  name: test-remote-10
spec:
  ports:
    - port: 8501
      protocol: TCP
      targetPort: 8501
  selector:
    app.kubernetes.io/instance: test-remote-10
